# 不想启动某个IM就注释掉那一部分

# QQ
[Controller.QQ]
master = [222111, 11424] # master user id , 账号 ID
account = 0
http_host = 'http://localhost:8080'   # Mirai http服务器
ws_host = 'http://localhost:8080'   # Mirai Websocket服务器
verify_key = ""
trigger = false
INTRO = "POWER BY OPENAI"  # 后缀
ABOUT = "Created by github.com/sudoskys/Openaibot" # 关于命令返回
WHITE = "Group NOT in WHITE list" # 黑白名单提示
proxy = { status = false, url = "http://127.0.0.1:7890" }

# Telegram
[Controller.Telegram]
master = [114, 514] # master user id , 账号 ID
botToken = '' # 机器人密钥
trigger = false
INTRO = "POWER BY OPENAI"  # 后缀
ABOUT = "Created by github.com/sudoskys/Openaibot" # 关于命令返回
WHITE = "Group NOT in WHITE list" # 黑白名单提示
# 设置的代理，但是不代理 openai api, 只代理 bot
proxy = { status = false, url = "http://127.0.0.1:7890" }

# 微信
[Controller.WeChat]
my_name = '机器人名字' # 机器人名字，需自行设定
master = ['yjsnpi_114514','tkgw_1919810'] # 管理员**微信号**。另外自己给自己发消息，默认按管理员处理
host_port = 'tcp://127.0.0.1:10086' # WcFerry C++后端url
debug = false # WcFerry 预留调试选项
trigger = false
INTRO = "POWER BY OPENAI"  # 后缀
ABOUT = "Created by github.com/sudoskys/Openaibot" # 关于命令返回
WHITE = "Group NOT in WHITE list" # 黑白名单提示
# 此代理配置无用。代理需用户在Windows客户端自行设置。为兼容性而保留
proxy = { status = false, url = 'http://114.51.4.19:19810' }

# Base Event Api
[Controller.BaseServer]
host = "127.0.0.1"
port = 9559
