name: Docker Image CI (dev)

on:
  workflow_dispatch:
  push:
    branches:
      - docker
      # - develop
      # - '**-develop'

jobs:
  build-and-push-image:
    if: contains('["sudoskys"]', github.actor)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            sudoskys/llmbot
          tags: |
            # set latest tag for default branch
            type=raw,value=latest
            type=ref,event=branch

          flavors: |
            latest=false
            suffix=-dev,onlatest=true

      - name: echo
        run: echo ${{ steps.meta.outputs.json }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}
          cache-to: type=inline
