name: Run tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - develop
      - '**-develop'

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.8.x, 3.9.x,3.10.x ,3.11.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: "x64"
      - name: Install dependencies
        run: |
          pip install poetry==1.6.1
          poetry install --all-extras
          python -m pip install pytest

      - name: Run tests
        run: |
          poetry install --all-extras
          cd test
          poetry run pytest